// Abbreviation definitions as DATA only. `make(..abbr-list)` must be called from the
// root document (main.typ): the abbr package only registers abbreviations when `make`
// runs in the same compilation root as `#a()`, not when called inside an imported module.
#let abbr-list = (
  ("DNN", "Deep neural network"),
  ("HD", "Huntington disease"),
  ("HAP40", "huntingtin-associated protein 40"),
  ("HTT", "huntingtin"),
  ("TP53", "tumour protein 53"),
  ("PINK1", "PTEN-induced kinase 1"),
  ("AP-MS", "affinity purification mass spectrometry"),
  ("LFQ", "label-free quantification"),
  ("RAB5", "Ras-related protein 5A"),
  ("SNAP", "soluble NSF attachment protein"),
  ("GFP", "green fluorescent protein"),
  ("DTT", "dithiothreitol"),
  ("EDTA", "ethylenediaminetetraacetic acid "),
  ("DSS", "disuccinimidyl suberate"),
  ("BFDR", "Bayesian false discovery rate"),
  ("polyQ", "polyglutamine"),
  ("ISR", "Integrated Stress Response"),
  ("SREBP1", "sterol regulatory element-binding protein 1"),
  ("SREBP2", "sterol regulatory element-binding protein 2"),
  ("PEI", "polyethyleneimine"),
  ("TEAB", "triethylammonium bicarbonate"),
  ("TCEP", "tris(2-carboxyethyl)phosphine hydrochloride"),
  ("CAA", "2-chloroacetamide"),
  ("GSEA", "Gene Set Enrichment Analysis"),
  ("HMGCS1", "3-hydroxy-3-methylglutaryl-CoA synthase 1"),
  ("AURKA", "Aurora kinase A"),
  ("CDKN1A", "cyclin-dependent kinase inhibitor 1A"),
  ("ATF4", "activating transcription factor 4"),
  ("DDIT3", "DNA-damage-inducible transcript 3"),
  ("PPP1R15A", "protein phosphatase 1, regulatory (inhibitor) subunit 15A"),
  ("TNRC6A", "Transcriptionally regulated RNA-binding protein 6A"),
  ("TNRC6B", "Transcriptionally regulated RNA-binding protein 6B"),
  ("HDSigDB", "Huntington’s Disease Signature Database"),
  ("RRHO", "Rank-Rank Hypergeometric Overlap"),
  ("DEG", "differentially expressed gene"),
  ("HEK293", "human embryonic kidney 293"),
  ("MNAR", "missing not at random"),
  ("MAR", "missing at random"),
  ("ECE", "expected calibration error"),
  ("MCE", "maximum calibration error"),
  ("PEP", "posterior error probability"),
  ("MCC", "Matthews correlation coefficient"),
  ("AUPRC", "area under the precision–recall curve"),
  ("MS", "mass spectrometry"),
  ("BMA", "Bayesian model averaging"),
  ("PPC", "posterior predictive check"),
  ("WAIC", "widely applicable information criterion"),
  ("JZS", "Jeffreys-Zellner-Siow"),
  ("KS", "Kolmogorov-Smirnov"),
  ("KL", "Kullback-Leibler"),
  ("OVL", "overlap coefficient"),
  ("LOO", "leave-one-out"),
  ("PSIS", "Pareto-smoothed importance sampling"),
  ("FDR", "false discovery rate"),
  ("PCA", "principal component analysis"),
  ("QC", "quality control"),
  ("BIC", "Bayesian information criterion"),
  ("EB", "Empirical Bayes"),
  ("EM", "expectation-maximisation"),
  ("MAP-EM", "maximum a posteriori expectation-maximisation"),
)
