#=
ProteinCoLoc: A Julia package for the analysis of protein co-localization in microscopy images
Copyright (C) 2023  Dr. rer. nat. Manuel Seefelder
E-Mail: manuel.seefelder@uni-ulm.de
Postal address: Department of Gene Therapy, University of Ulm, Helmholzstr. 8/1, 89081 Ulm, Germany

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as published
by the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.
=#

# spike/simulator/ghat.jl --- FROZEN induced-μ inverse map ĝ : μ ↦ ρ_true (SIM-02).
# AUTO-GENERATED by spike/simulator/calibration.jl -- DO NOT EDIT BY HAND; re-run
# `julia --project=spike spike/simulator/calibration.jl` to regenerate.
#
# HAND-PATCH PROVENANCE (2026-07-25): the "real anchor" / "negative tail" block below
# was corrected BY HAND, deliberately and as the only exception to the banner above.
# Re-running calibration.jl would re-run the stochastic sweep and RE-FIT the map,
# changing the frozen GHAT_* knots -- which is forbidden. The wording below is copied
# verbatim from the (already-corrected) calibration.jl emit template, so a future
# regeneration is a no-op on this block. GHAT_MU_KNOTS, GHAT_RHO_KNOTS, GHAT_MU_MIN,
# GHAT_MU_MAX and ghat() are byte-identical to the generated artifact; nothing outside
# the comment header was touched.
#
# HAND-PATCH PROVENANCE (2026-07-25, second entry): the same "real anchor" / "negative
# tail" block was hand-patched AGAIN, this time to change the measured CHANNEL PAIR from
# c1/c2 to c2/c3. test/runtests.jl:105 records the fixture channels as ["blue","green",
# "red"], so c1 is the DAPI/Hoechst nuclear COUNTERSTAIN and every c1 pair measured
# counterstain-vs-protein overlap rather than colocalization. The reason for hand-patching
# is unchanged: re-running calibration.jl would re-run the stochastic sweep and RE-FIT the
# map, changing the frozen GHAT_* knots -- forbidden. The wording below is again copied
# verbatim from the corrected calibration.jl emit template, so a future regeneration stays
# a no-op on this block, and the knots and ghat() remain byte-identical.
#
# ĝ is a clamped piecewise-linear interpolation of the monotone (isotonic-regressed)
# induced-μ sweep, inverted so prior.jl can draw μ*~Truncated(Cauchy(0,0.3),-1,1) and
# set ρ_true = ghat(μ*). Monotone by construction (knots strictly increasing in μ).
#
# CALIBRATION EVIDENCE (frozen; transcribed into spike/NOTES.md §3):
#   generator        : shared-latent correlated smooth Gaussian field (forward.jl, D-15)
#   sweep            : ρ_true ∈ [−0.99, 0.99], 25 points, n_per=100, size=(512, 512) (D-08/D-09)
#   span past ±0.9   : induced μ at knob ±0.9 ≈ ±0.76 post-degrade ⇒ knob extended past ±0.9 (D-15)
#   induced μ range  : [-0.6798, 0.8471]  (the physically-realized range, D-16)
#   monotonicity     : corspearman(ρ_grid, E[μ]) = 1.0
#   SIM-02 match     : Wasserstein-1 = 0.05228 (tol 0.1), KS = 0.10123 (tol 0.2) over the realized range (D-16); n=300
#   size-invariance  : max |Δ E[μ]| vs 512² across {256²,512²,1024²} = 0.0318
#   σ/τ consistency  : induced per-patch-corr pooled SD = 0.3169 (within Truncated(Cauchy(0.1,0.3),1e-4,1): true)
#   ν consistency    : per-patch-corr excess kurtosis = -0.0518 (>0 ⇒ heavier-than-Gaussian ⇒ finite-ν Exponential plausible)
#   real anchor (D-16): faithful LoadImages.jl load_tiff (NOT luminance), measured BOTH ways
#     channel pair     : c2/c3 = green/red  (ANCHOR_CHANNEL_PAIR = (2, 3))
#     channel map (test/runtests.jl:105): c1 = blue (DAPI/Hoechst nuclear counterstain), c2 = green, c3 = red
#     why the pair matters: c1 is a nuclear COUNTERSTAIN, not a target protein, so any pair
#       involving it measures counterstain-vs-protein overlap and NOT colocalization. The earlier
#       figures (positive 0.3292 / negative 0.2481, unmasked c1/c2) were measured against the
#       counterstain and are SUPERSEDED, not merely updated.
#     UNMASKED (what patch_summary / the v2.0 training + inference path sees -- no Otsu mask):
#       positive μ = 0.4603 (64/64 patches), negative μ = 0.3815 (64/64 patches)
#     MASKED (the v1.0 analysis pipeline: per-channel Otsu _apply_mask! then _exclude_zero):
#       positive μ = 0.8238 (22/64 patches), negative μ = -0.0338 (20/64 patches)
#   anchor caveat    : on this pair the two estimators AGREE in order -- positive > negative under
#     BOTH -- and the MASKED pair separates the controls far more sharply (0.8238 vs
#     -0.0338) than the unmasked pair does (0.4603 vs 0.3815). Both still carry biases:
#     - UNMASKED is biased POSITIVE: background pixels are dark in both channels and co-vary,
#       so the shared background alone lifts the per-patch correlation. On this pair that also
#       COMPRESSES the contrast between the controls, which is why the unmasked pair barely
#       separates them.
#     - MASKED carries a RANGE-RESTRICTION caveat: each channel is thresholded INDEPENDENTLY and
#       _exclude_zero then keeps only pixels bright in BOTH -- a selection on both variables,
#       which can attenuate or distort the correlation. This is the known weakness of thresholded
#       Pearson (the reason Manders/Costes coefficients exist), and masking leaves only ~20-22 of
#       64 patches above the >=15-survivor floor. The earlier "MASKED is biased NEGATIVE" framing
#       OVERSTATED it: here the masked POSITIVE control reads 0.8238, so the selection does
#       not prevent detecting strong colocalization -- the large negative readings that motivated
#       that wording were predominantly the wrong-channel (counterstain) artifact, not the mask.
#   negative tail    : neg_reachable (masked negative-fixture μ < 0, on the configured pair) = true.
#     STILL NOT ESTABLISHED either way. The masked negative fixture reads -0.0338, which is
#     approximately ZERO rather than convincingly negative, and n = 2 fixtures cannot settle
#     whether a negative induced-μ tail is physically reachable. The former unqualified
#     "physically reachable = false => PRIOR-ONLY" reading stays WITHDRAWN and is NOT reinstated;
#     equally, the clean +0.82 / -0.03 control separation is NOT evidence for the opposite
#     claim. The SIM-02 consistency claim stays scoped to the realized range
#     [GHAT_MU_MIN, GHAT_MU_MAX]; that scoping is unchanged and does not depend on this anchor.

const GHAT_MU_KNOTS  = [-0.67976, -0.626569, -0.538958, -0.488021, -0.415148, -0.359152, -0.295677, -0.227874, -0.152285, -0.102842, -0.033647, 0.028099, 0.086485, 0.159778, 0.208655, 0.273921, 0.328753, 0.4088, 0.469433, 0.519385, 0.586926, 0.652623, 0.717369, 0.787807, 0.847149]

const GHAT_RHO_KNOTS = [-0.99, -0.9075, -0.825, -0.7425, -0.66, -0.5775, -0.495, -0.4125, -0.33, -0.2475, -0.165, -0.0825, 0.0, 0.0825, 0.165, 0.2475, 0.33, 0.4125, 0.495, 0.5775, 0.66, 0.7425, 0.825, 0.9075, 0.99]

# Physically-realized induced-μ range (D-16): the span the SIM-02 consistency claim
# is scoped over. μ outside this range clamps ρ_true to the corresponding endpoint.
const GHAT_MU_MIN = -0.67976
const GHAT_MU_MAX = 0.847149

"""
    ghat(μ::Real) -> Float64

The frozen monotone induced-μ inverse: maps a target per-patch-correlation mean μ
to the ρ_true knob that induces it (E[induced μ | ρ_true] = μ). Clamped piecewise
linear; monotone non-decreasing. μ beyond [GHAT_MU_MIN, GHAT_MU_MAX] clamps ρ_true
to the nearest swept endpoint.
"""
function ghat(μ::Real)
    knots = GHAT_MU_KNOTS
    vals  = GHAT_RHO_KNOTS
    μ <= knots[1]   && return vals[1]
    μ >= knots[end] && return vals[end]
    i = searchsortedlast(knots, μ)
    t = (μ - knots[i]) / (knots[i+1] - knots[i])
    return vals[i] + t * (vals[i+1] - vals[i])
end
