#=
ProteinCoLoc: A Julia package for the analysis of protein co-localization in microscopy images
Copyright (C) 2023  Dr. rer. nat. Manuel Seefelder
E-Mail: manuel.seefelder@uni-ulm.de
Postal address: Department of Gene Therapy, University of Ulm, Helmholzstr. 8/1, 89081 Ulm, Germany

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as published
by the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.
=#

# spike/simulator/ghat.jl --- FROZEN induced-μ inverse map ĝ : μ ↦ ρ_true (SIM-02).
# AUTO-GENERATED by spike/simulator/calibration.jl -- DO NOT EDIT BY HAND; re-run
# `julia --project=spike spike/simulator/calibration.jl` to regenerate.
#
# ĝ is a clamped piecewise-linear interpolation of the monotone (isotonic-regressed)
# induced-μ sweep, inverted so prior.jl can draw μ*~Truncated(Cauchy(0,0.3),-1,1) and
# set ρ_true = ghat(μ*). Monotone by construction (knots strictly increasing in μ).
#
# CALIBRATION EVIDENCE (frozen; transcribed into spike/NOTES.md §3):
#   generator        : shared-latent correlated smooth Gaussian field (forward.jl, D-15)
#   sweep            : ρ_true ∈ [−0.99, 0.99], 25 points, n_per=100, size=(512, 512) (D-08/D-09)
#   span past ±0.9   : induced μ at knob ±0.9 ≈ ±0.76 post-degrade ⇒ knob extended past ±0.9 (D-15)
#   induced μ range  : [-0.6798, 0.8471]  (the physically-realized range, D-16)
#   monotonicity     : corspearman(ρ_grid, E[μ]) = 1.0
#   SIM-02 match     : Wasserstein-1 = 0.05228 (tol 0.1), KS = 0.10123 (tol 0.2) over the realized range (D-16); n=300
#   size-invariance  : max |Δ E[μ]| vs 512² across {256²,512²,1024²} = 0.0318
#   σ/τ consistency  : induced per-patch-corr pooled SD = 0.3169 (within Truncated(Cauchy(0.1,0.3),1e-4,1): true)
#   ν consistency    : per-patch-corr excess kurtosis = -0.0518 (>0 ⇒ heavier-than-Gaussian ⇒ finite-ν Exponential plausible)
#   real anchor (D-16): faithful LoadImages.jl load_tiff (NOT luminance): positive μ = 0.3292, negative μ = 0.2481
#   negative tail    : physically reachable in real fluorescence = false ⇒ negative μ-prior tail documented PRIOR-ONLY; consistency scoped to realized range

const GHAT_MU_KNOTS  = [-0.67976, -0.626569, -0.538958, -0.488021, -0.415148, -0.359152, -0.295677, -0.227874, -0.152285, -0.102842, -0.033647, 0.028099, 0.086485, 0.159778, 0.208655, 0.273921, 0.328753, 0.4088, 0.469433, 0.519385, 0.586926, 0.652623, 0.717369, 0.787807, 0.847149]

const GHAT_RHO_KNOTS = [-0.99, -0.9075, -0.825, -0.7425, -0.66, -0.5775, -0.495, -0.4125, -0.33, -0.2475, -0.165, -0.0825, 0.0, 0.0825, 0.165, 0.2475, 0.33, 0.4125, 0.495, 0.5775, 0.66, 0.7425, 0.825, 0.9075, 0.99]

# Physically-realized induced-μ range (D-16): the span the SIM-02 consistency claim
# is scoped over. μ outside this range clamps ρ_true to the corresponding endpoint.
const GHAT_MU_MIN = -0.67976
const GHAT_MU_MAX = 0.847149

"""
    ghat(μ::Real) -> Float64

The frozen monotone induced-μ inverse: maps a target per-patch-correlation mean μ
to the ρ_true knob that induces it (E[induced μ | ρ_true] = μ). Clamped piecewise
linear; monotone non-decreasing. μ beyond [GHAT_MU_MIN, GHAT_MU_MAX] clamps ρ_true
to the nearest swept endpoint.
"""
function ghat(μ::Real)
    knots = GHAT_MU_KNOTS
    vals  = GHAT_RHO_KNOTS
    μ <= knots[1]   && return vals[1]
    μ >= knots[end] && return vals[end]
    i = searchsortedlast(knots, μ)
    t = (μ - knots[i]) / (knots[i+1] - knots[i])
    return vals[i] + t * (vals[i+1] - vals[i])
end
