#=
ProteinCoLoc: A Julia package for the analysis of protein co-localization in microscopy images
Copyright (C) 2023  Dr. rer. nat. Manuel Seefelder

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as published
by the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.
=#

#############################################################################################
# src/amortized/simulator.jl --- the Phase-2 forward physics simulator, PROMOTED into src/.
#
# Promoted VERBATIM (prior ranges + physics unchanged) from the proven spike:
#   spike/simulator/ghat.jl    -> ghat, GHAT_MU_KNOTS/RHO_KNOTS (frozen induced-μ inverse)
#   spike/simulator/prior.jl   -> sample_prior (π(θ), the 8-field NamedTuple: the 7 D-04 fields
#                                 plus `chromatic_eps`, D-09)
#   spike/simulator/forward.jl -> simulate_pair (the 7-stage 2-channel 2D forward model)
#   spike/contract.jl:60-70    -> build_mci (2-channel matrices -> MultiChannelImage)
#
# WHY PROMOTED HERE (07-05): `datagen.jl` (`generate_sample`) and the ship-gate harness
# (`default_simulator()`) reference `sample_prior` / `simulate_pair` / `build_mci` inside function
# bodies ONLY — they were injectable seams until a per-grid pipeline needed REAL 8×8 data. Running
# `_train_grid_pipeline(8)` on the default (real) datagen requires the forward model in src/.
#
# HARD CONSTRAINT (CLAUDE.md prior-consistency): the simulator prior π(θ) is kept BYTE-CONSISTENT
# with the existing Turing @model prior ranges (μ via MU_PRIOR = Truncated(Cauchy(0,0.3),-1,1), and
# the induced-μ inverse ĝ) — the ranges below are copied unchanged from the spike, NOT re-tuned, so
# the amortized path stays ADVI-comparable. ĝ is the FROZEN calibration artifact (do NOT hand-edit).
#
# REPRODUCIBILITY (D-11/D-14): every draw is an explicit function of the threaded `rng`
# (Philox-per-index upstream), so parallel datagen is byte-identical to serial for any thread count.
#############################################################################################

import Distributions: Truncated, Cauchy, Uniform, Bernoulli, Poisson, Normal
import Random: AbstractRNG
import Statistics: mean, std
import ImageFiltering: imfilter, Kernel
import ImageTransformations: warp
import CoordinateTransformations: Translation, LinearMap, recenter
import Interpolations: BSpline, Linear

# =============================== FROZEN induced-μ inverse ĝ (SIM-02) =========================
# AUTO-GENERATED by spike/simulator/calibration.jl — a clamped piecewise-linear interpolation of
# the monotone (isotonic-regressed) induced-μ sweep, inverted so `sample_prior` can draw
# μ*~Truncated(Cauchy(0,0.3),-1,1) and set ρ_true = ghat(μ*). Monotone by construction. DO NOT EDIT
# BY HAND — regenerate via the spike calibration script. Calibration evidence (frozen):
#   Wasserstein-1 = 0.05228 (tol 0.1) over the realized μ-range; corspearman(ρ_grid,E[μ]) = 1.0.

const GHAT_MU_KNOTS  = [-0.67976, -0.626569, -0.538958, -0.488021, -0.415148, -0.359152, -0.295677, -0.227874, -0.152285, -0.102842, -0.033647, 0.028099, 0.086485, 0.159778, 0.208655, 0.273921, 0.328753, 0.4088, 0.469433, 0.519385, 0.586926, 0.652623, 0.717369, 0.787807, 0.847149]

const GHAT_RHO_KNOTS = [-0.99, -0.9075, -0.825, -0.7425, -0.66, -0.5775, -0.495, -0.4125, -0.33, -0.2475, -0.165, -0.0825, 0.0, 0.0825, 0.165, 0.2475, 0.33, 0.4125, 0.495, 0.5775, 0.66, 0.7425, 0.825, 0.9075, 0.99]

# Physically-realized induced-μ range (D-16): the span the SIM-02 consistency claim is scoped over.
const GHAT_MU_MIN = -0.67976
const GHAT_MU_MAX = 0.847149

"""
    ghat(μ::Real) -> Float64

The frozen monotone induced-μ inverse: maps a target per-patch-correlation mean μ to the ρ_true
knob that induces it (E[induced μ | ρ_true] = μ). Clamped piecewise linear; monotone
non-decreasing. μ beyond [GHAT_MU_MIN, GHAT_MU_MAX] clamps ρ_true to the nearest swept endpoint.
"""
function ghat(μ::Real)
    knots = GHAT_MU_KNOTS
    vals  = GHAT_RHO_KNOTS
    μ <= knots[1]   && return vals[1]
    μ >= knots[end] && return vals[end]
    i = searchsortedlast(knots, μ)
    t = (μ - knots[i]) / (knots[i+1] - knots[i])
    return vals[i] + t * (vals[i+1] - vals[i])
end

# =============================== the simulator prior π(θ) (SIM-02) ===========================
# The Turing μ-prior (src/bayes.jl ~274-291), the SIM-02 consistency target — copied UNCHANGED.
const MU_PRIOR = Truncated(Cauchy(0.0, 0.3), -1.0, 1.0)

# Pre-declared SIM-02 pass bar (documentation only here; enforced in the spike calibration).
const SIM02_W1_TOL = 0.10

# Nuisance prior ranges (D-03) — MIRROR of the spike calibration's `_sample_nuisances`; copied
# UNCHANGED so the induced-μ spread the calibration averaged over is reproduced exactly.
const SPILLOVER_PRIOR        = Uniform(0.0, 0.2)   # directional bleed-through (modest)
const AUTOFLUORESCENCE_PRIOR = Uniform(0.0, 0.1)   # additive background offset
const LABEL_EFFICIENCY_PRIOR = Uniform(0.6, 1.0)   # Bernoulli keep-probability
const SHIFT_PRIOR            = Uniform(-1.0, 1.0)  # sub-pixel registration error (dx, dy); ±1, see below
const CHROMATIC_PRIOR        = Uniform(-0.02, 0.02) # radial chromatic scale (D-09/D-11), see below
const NOISE_PRIOR            = Uniform(0.0, 1.0)   # Poisson+Gaussian noise scale

# SHIFT PRIOR SCOPE (ruling Q2 / D-02): the spike's Phase-11 RESEARCH prior widens the shift range
# to ±3 px, and that widening is DELIBERATELY NOT MIRRORED here. D-02 scopes it to the research
# net; D-11 mirrors ONLY the chromatic term. Widening this line would desynchronise
# `theta_prior_bounds()[5:6]` from the shipped bundle's FROZEN `theta_zt.lo`/`.hi` (persisted
# training-time data, architecture.jl:100-104), a silent semantic drift on the reconstruct path.
#
# CHROMATIC PRIOR (D-09): a 1-parameter RADIAL magnification difference between the channels —
# zero at the image centre, maximal at the corners — which a global dx/dy translation cannot
# represent. On a 256² field the half-diagonal is ≈181 px, so corner displacement ≈ ε·181
# (0.02 → ≈3.6 px), magnitude-comparable to the registration-shift range. SYMMETRIC because
# channel ordering is the USER's choice, not the model's.
#
# PROVENANCE (D-12): `simulator.jl` is a `DATAGEN_HASH_SRC_FILES` member (datagen.jl:208-213), so
# adding this parameter re-digests the training-data cache directory and orphans the pool the
# shipped 8×8 net was trained from. The shipped net's training distribution is pinned BY GIT
# REFERENCE instead — see named limit #8 in `docs/amortized.md`. The artifact is unaffected (it is
# pinned by `git-tree-sha1` in `Artifacts.toml`, not by the datagen digest).

"""
    sample_prior(rng::AbstractRNG) -> NamedTuple

Draw one θ from the simulator prior π(θ) (the 8-field NamedTuple: the 7 D-04 fields plus
`chromatic_eps`, D-09). The colocalization knob is set through the frozen induced-μ inverse:

  μ* ~ Truncated(Cauchy(0,0.3),-1,1)      # the Turing μ-prior (MU_PRIOR)
  ρ_true = ghat(μ*)                        # so E[induced μ | ρ_true] = μ*

and the 7 nuisances are drawn from their own priors. Deterministic under a fixed `rng` (D-14). The
result flows straight into `simulate_pair(rng, θ; imsize)`.

**`chromatic_eps` is APPENDED AT THE END of the field order, never slotted beside
`shift_dx`/`shift_dy`.** θ is consumed POSITIONALLY downstream (`collect(values(θ))` is the θ→row
map in `datagen.jl`; `ood.jl` `_theta_tuple` indexes `v[1]..v[7]`), so appending is what keeps
every pre-existing row index valid.
"""
function sample_prior(rng::AbstractRNG)
    μ_star = rand(rng, MU_PRIOR)
    return (
        ρ_true           = ghat(μ_star),
        spillover        = rand(rng, SPILLOVER_PRIOR),
        autofluorescence = rand(rng, AUTOFLUORESCENCE_PRIOR),
        label_efficiency = rand(rng, LABEL_EFFICIENCY_PRIOR),
        shift_dx         = rand(rng, SHIFT_PRIOR),
        shift_dy         = rand(rng, SHIFT_PRIOR),
        noise            = rand(rng, NOISE_PRIOR),
        chromatic_eps    = rand(rng, CHROMATIC_PRIOR),   # D-09: appended LAST (positional θ)
    )
end

"""
    theta_prior_bounds() -> NTuple{8,Tuple{Float64,Float64}}

The SUPPORT BOX of the simulator prior π(θ), in `sample_prior` FIELD ORDER (θ row order:
ρ_true, spillover, autofluorescence, label_efficiency, shift_dx, shift_dy, noise, chromatic_eps).

**SINGLE SOURCE OF TRUTH.** Every bound is DERIVED from the prior objects defined above — the
nuisance bounds from `Distributions.minimum/maximum` of the very `Uniform`s `sample_prior` draws
from, and the ρ_true bounds from the extrema of the frozen `GHAT_RHO_KNOTS` (ρ_true = `ghat(μ*)`
is a CLAMPED piecewise-linear map, so its exact range is the first/last ρ knot, attained with
positive probability at both ends). Nothing here is a duplicated literal: change a prior above and
this box follows.

Consumed by `BoundedThetaTransform` (architecture.jl) to map θ into an unconstrained space for the
`NormalisingFlow` and back, so posterior draws are guaranteed to lie inside the prior support
(07-CALIBRATION-FINDINGS F2: the unbounded flow cannot represent a truncated box and its learned
conditional drifts off-centre).
"""
theta_prior_bounds() = (
    (first(GHAT_RHO_KNOTS), last(GHAT_RHO_KNOTS)),                       # ρ_true = ghat(μ*)
    (minimum(SPILLOVER_PRIOR),        maximum(SPILLOVER_PRIOR)),
    (minimum(AUTOFLUORESCENCE_PRIOR), maximum(AUTOFLUORESCENCE_PRIOR)),
    (minimum(LABEL_EFFICIENCY_PRIOR), maximum(LABEL_EFFICIENCY_PRIOR)),
    (minimum(SHIFT_PRIOR),            maximum(SHIFT_PRIOR)),             # shift_dx
    (minimum(SHIFT_PRIOR),            maximum(SHIFT_PRIOR)),             # shift_dy
    (minimum(NOISE_PRIOR),            maximum(NOISE_PRIOR)),
    (minimum(CHROMATIC_PRIOR),        maximum(CHROMATIC_PRIOR)),           # chromatic_eps (D-09)
)

# =============================== the 2-channel 2D forward model (SIM-01) =====================
# Fixed nuisance constants (copied UNCHANGED from spike/simulator/forward.jl).
const σ_psf      = 1.3      # diffraction-limited fixed PSF (D-05), ≈1.0-1.5 px
const STRUCT_σ   = 6.0      # field-smoothing scale; MUST be ≫ σ_psf (D-15)
const GAIN       = 50.0     # Poisson shot gain
const READ_NOISE = 0.01     # Gaussian read-noise sd
const BG_FLOOR   = 0.02     # small-positive background floor (keeps pixels > 0)

# Numerically-stable softplus = log(1 + exp(x)); the nonneg intensity transform.
_softplus(x::Real) = log1p(exp(-abs(x))) + max(x, zero(x))

"""
    _smooth_field(rng, imsize) -> Matrix{Float64}

A single smooth latent Gaussian field: white noise low-pass-filtered at the STRUCT_σ structural
scale, then standardized to zero-mean / unit-variance (load-bearing, D-15: restores amplitude the
Gaussian smoothing collapses so the linear mix carries correlation into the softplus transform).
"""
function _smooth_field(rng::AbstractRNG, imsize::Tuple{Int,Int})
    f = imfilter(randn(rng, imsize...), Kernel.gaussian(STRUCT_σ))
    # IN-03: floor the denominator at 1e-10 (a near-zero std would otherwise blow the field up).
    return (f .- mean(f)) ./ max(std(f), 1e-10)
end

"""
    simulate_pair(rng::AbstractRNG, θ; imsize=(256,256)) -> Vector{Matrix{Float64}}

Generate a 2-channel microscopy image pair from the 8-field θ NamedTuple (the 7 D-04 fields plus
`chromatic_eps`, D-09) by running the seven D-06 stages in order on the explicitly-threaded `rng`
(D-14): (1) shared-latent correlated smooth Gaussian fields (D-15; `sign(ρ)` on channel-2's shared
component makes anti-correlation reachable at negative ρ_true), (2) Bernoulli thinning, (3) fixed
Gaussian PSF, (4) directional spillover, (5) autofluorescence + background floor, (6) ONE composed
affine misregistration of ch2 — radial chromatic scale about the image centre composed with the
sub-pixel registration shift, in a SINGLE resampling pass (D-10) — (7) Poisson+Gaussian noise.
Returns `[ch1, ch2]`, each `imsize`, all finite and ≥ 0 with a small-positive background. Throws
`ArgumentError` on out-of-range θ or `imsize` dim < 64.

**A legacy 7-field θ remains a valid input**, read as `chromatic_eps = 0` and reproducing the
pre-D-09 output bit for bit — the compatibility contract the posterior-predictive OOD channel
(`ood.jl` `_theta_tuple`, which reconstructs θ from a 7-row posterior mean) depends on.
"""
function simulate_pair(rng::AbstractRNG, θ; imsize::Tuple{Int,Int} = (256, 256))
    # --- θ / imsize validation at entry (T-02-IV: untrusted parameter vector) ---
    (imsize[1] ≥ 64 && imsize[2] ≥ 64) ||
        throw(ArgumentError("imsize dims must be ≥ 64 for the patch grid to produce " *
                            "non-missing patches (>15 px each), got $imsize"))
    # D-09 backward compatibility: `chromatic_eps` is read through ONE defensive local binding
    # shared by the guard below and stage 6, so a legacy 7-field θ (e.g. `ood.jl` `_theta_tuple`
    # on a 7-row posterior mean) stays valid and means "no chromatic aberration".
    chromatic_eps_val = hasproperty(θ, :chromatic_eps) ? θ.chromatic_eps : 0.0
    all(isfinite, (θ.ρ_true, θ.spillover, θ.autofluorescence, θ.label_efficiency,
                   θ.shift_dx, θ.shift_dy, θ.noise, chromatic_eps_val)) ||
        throw(ArgumentError("all θ fields must be finite, got $θ"))
    (-1.0 ≤ θ.ρ_true ≤ 1.0) ||
        throw(ArgumentError("ρ_true must be in [-1, 1], got $(θ.ρ_true)"))
    (0.0 ≤ θ.spillover ≤ 1.0) ||
        throw(ArgumentError("spillover must be in [0, 1], got $(θ.spillover)"))
    (0.0 ≤ θ.autofluorescence) ||
        throw(ArgumentError("autofluorescence must be ≥ 0, got $(θ.autofluorescence)"))
    (0.0 ≤ θ.label_efficiency ≤ 1.0) ||
        throw(ArgumentError("label_efficiency must be in [0, 1], got $(θ.label_efficiency)"))
    (0.0 ≤ θ.noise) ||
        throw(ArgumentError("noise must be ≥ 0, got $(θ.noise)"))
    # D-09: stage 6's backward scale is s = 1/(1 + chromatic_eps), so 1 + chromatic_eps must stay
    # STRICTLY POSITIVE — at -1 it divides by zero, below -1 the affine map MIRRORS channel 2.
    (-1.0 < chromatic_eps_val) ||
        throw(ArgumentError("chromatic_eps must be > -1 (so 1 + chromatic_eps stays positive), " *
                            "got $(chromatic_eps_val)"))

    ρ = θ.ρ_true

    # --- (1) shared-latent correlated smooth Gaussian fields (D-15) -------------
    L  = _smooth_field(rng, imsize)
    ε1 = _smooth_field(rng, imsize)
    ε2 = _smooth_field(rng, imsize)
    a  = sqrt(abs(ρ))           # shared-component weight
    b  = sqrt(1.0 - abs(ρ))     # private-component weight  (a² + b² = 1)
    ch1 = _softplus.(a .* L .+ b .* ε1)
    ch2 = _softplus.(sign(ρ) .* a .* L .+ b .* ε2)

    # --- (2) Bernoulli thinning (label_efficiency = keep-probability) -----------
    p     = clamp(θ.label_efficiency, 0.0, 1.0)
    keep1 = rand(rng, Bernoulli(p), imsize...)
    keep2 = rand(rng, Bernoulli(p), imsize...)
    ch1 .= ch1 .* keep1
    ch2 .= ch2 .* keep2

    # --- (3) fixed Gaussian PSF (D-05 nuisance; width is NOT read from θ) --------
    psf = Kernel.gaussian(σ_psf)
    ch1 = imfilter(ch1, psf)
    ch2 = imfilter(ch2, psf)

    # --- (4) 2×2 directional spillover (bleed-through, directional ≠ symmetric) --
    ch1 = ch1 .+ θ.spillover .* ch2

    # --- (5) autofluorescence offset + small-positive background floor ----------
    ch1 = ch1 .+ θ.autofluorescence .+ BG_FLOOR
    ch2 = ch2 .+ θ.autofluorescence .+ BG_FLOOR

    # --- (6) ONE composed affine on ch2: radial chromatic scale ∘ registration shift (D-10) ----
    # WR-06 (RE-DERIVED for the composed map). `warp` is BACKWARD-mode — out[I] = ch2[A(I)] —
    # so `A` maps a DESTINATION index to the SOURCE index it samples and the CONTENT undergoes
    # A⁻¹. Hence (a) the Translation slot order is unchanged (slot 1 = rows = dy, slot 2 = cols
    # = dx), and (b) MAGNIFYING content by (1 + chromatic_eps) about the centre requires the
    # backward map to SHRINK coordinates: s = 1/(1 + chromatic_eps), positive by the guard above.
    # `recenter(t, c) == Translation(c) ∘ t ∘ Translation(-c)` puts the scale centre at the
    # geometric centre of axes(ch2); the composition COLLAPSES to a single AffineMap, so exactly
    # ONE interpolation pass runs. One pass is a correctness requirement (D-10): each resampling
    # pass smooths, and smoothing decorrelates. At chromatic_eps = 0 the linear part is the exact
    # identity, so the output is bit-identical to the previous translation-only stage.
    s = 1.0 / (1.0 + chromatic_eps_val)
    c = map(ax -> (first(ax) + last(ax)) / 2, axes(ch2))
    A = Translation(θ.shift_dy, θ.shift_dx) ∘ recenter(LinearMap([s 0.0; 0.0 s]), c)
    shifted = warp(ch2, A, axes(ch2); method = BSpline(Linear()), fillvalue = BG_FLOOR)
    ch2 = Matrix{Float64}(collect(shifted))

    # --- (7) Poisson(shot) + Gaussian(read) noise (scaled by θ.noise) -----------
    read_sd = max(READ_NOISE * θ.noise, 0.0)
    ch1 = Float64.(rand.(Ref(rng), Poisson.(GAIN .* max.(ch1, 0.0)))) ./ GAIN .+
          rand(rng, Normal(0.0, read_sd), imsize)
    ch2 = Float64.(rand.(Ref(rng), Poisson.(GAIN .* max.(ch2, 0.0)))) ./ GAIN .+
          rand(rng, Normal(0.0, read_sd), imsize)

    return [Matrix{Float64}(max.(ch1, 0.0)), Matrix{Float64}(max.(ch2, 0.0))]
end

# =============================== summary-contract bridge (SIM-03) ============================

"""
    build_mci(data::Vector{Matrix{Float64}}; name="sim") -> MultiChannelImage

Build a `MultiChannelImage` from a 2-element vector of channel matrices, mirroring the convenience
constructor at `src/LoadImages.jl`. Per D-11, `pixel_size = size(data[1])` is the (W,H)
pixel-dimension tuple (NOT micrometers). The flow `build_mci(simulate_pair(...))` feeds
`patch_summary(mci, G)` unchanged.
"""
function build_mci(data::Vector{Matrix{Float64}}; name::String = "sim")
    @assert length(data) == 2 "simulator build_mci expects exactly 2 channels, got $(length(data))"
    return MultiChannelImage(
        data,
        ["ch1", "ch2"],
        name,
        ["", ""],
        size(data[1]),                 # D-11: pixel-dim tuple, not micrometers
        Images.otsu_threshold.(data),  # mirrors src/LoadImages.jl convenience ctor
    )
end
